name: 'Say hello'
description: 'Greet someone'
inputs:
  name:
    description: "Someone's name"
    required: true
    default: 'Somebody'
outputs:
  reply:
    value: ${{ steps.use-node-to-run.outputs.reply }}

runs:
  steps:
    - name: use node20 to run action
      id: use-node-to-run
      using: 'node20'
      main: 'index.js'