name: 'Say hello'
description: 'Greet someone'
inputs:
  name:
    description: "Someone's name"
    required: true
    default: 'Somebody'
outputs:
  reply:

runs:
  using: 'node20'
  main: 'index.js'