name: 'Say hello'
description: 'Greet someone'
inputs:
  name:
    description: "Someone's name"
    required: true
    default: 'Somebody'
outputs:
  reply:
    value: "aaa"

runs:
  id: use-node-to-run
  using: 'node20'
  main: 'index.js'