name: Deploy to github page

on:
  push:
    tags:        
      - 'trial@\d+.\d+.\d+'
  workflow_dispatch:

env: 
  jiraToken: ${{ secrets.JIRA_TOKEN }}
  jiraDomain: ${{ secrets.JIRA_DOMAIN }}
  foo: 'this is foo'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: # 一定要定義outputs，才能讓caller取用
      bar: ${{ steps.print.outputs.bar }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract version
        id: extract_version
        run: echo "${{github.ref_name}}" > ./src/version.txt
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src
          name: github-pages
      - name: 
        id: print
        run: |
          # echo ref_name: ${{github.ref_name}}
          echo build step is completed
          # echo "bar=$JIRA_DOMAIN || 'zzz'" >> $GITHUB_OUTPUT
          echo "bar=${{env.jiraDomain || 'zzz'}}" >> $GITHUB_OUTPUT
          echo ${{env.jiraDomain}}
          echo $bar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: https://tempura327.github.io/try-github-actions/
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: print
        run: |
          echo $jiraDomain
          echo ${{github.env.jiraDomain}}

# JIRA_DOMAIN、傳不進去，失敗
  update-release-note:
    needs: build
    # steps: 
    # 先clone repo才能用composite action
      # - uses: actions/checkout@v4
      # composite action，記得要有index.js
      # - uses: ./.github/actions/release-jira-release-note
      #   with:
      #     version: ${{github.ref_name}}

    # reusable workflow
    uses: tempura327/try-github-actions/.github/workflows/release-jira-release-note.yml@master
    with:
      version: ${{github.ref_name}}
      # 不要直接取用secret，會取不到secret
      # JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
      # JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
      # 錯誤
      # JIRA_TOKEN: ${{github.env.jiraToken}}
      # JIRA_TOKEN: $jiraToken
      JIRA_TOKEN: ${{needs.build.outputs.bar}}
      JIRA_DOMAIN:  ${{needs.build.outputs.bar}}
      foo: 'abcdefg'
    # env: 
    #   jiraToken: ${{ secrets.JIRA_TOKEN }}
    #   jiraDomain: ${{ secrets.JIRA_DOMAIN }}
    #   foo: 'this is foo'
  