name: Deploy to github page

on:
  push:
    tags:        
      - 'trial@\d.\d.\d'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract version
        id: extract_version
        run: echo "${{github.ref_name}}" > ./src/version.txt
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src
          name: versionData
      - name: print
        run: |
          echo ref_name: ${{github.ref_name}}
          echo build step is completed

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: https://tempura327.github.io/try-github-actions/
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4