name: CI
on:
  # workflow_run:
  #   workflows:
  #     - 'Deploy to github page'
  #   types:
  #     - completed
  workflow_dispatch:
  push:
    # branches:
      # - master
  pull_request:


jobs:
  check-performance:
    runs-on: ubuntu-latest
    steps:
      # lighthouse要跑瀏覽器，會失敗
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      # - run: |
      #     npm i -g lighthouse
      #   shell: bash
      # - name: run lighthouse
      #   run: |
      #     lighthouse https://try-github-actions-git-master-tempura327s-projects.vercel.app/

      # lighthouse
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install && npm install -g @lhci/cli@0.14.0
      - name: run-check
        run: | 
          lhci autorun --outputDir=./lighthouse-check-results
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}


      # lighthouse-ci
      # 失敗Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/try-github-actions/try-github-actions/lighthouserc.js from /opt/hostedtoolcache/node/18.20.4/x64/lib/node_modules/@lhci/cli/node_modules/@lhci/utils/src/lighthouserc.js not supported.
      # - uses: actions/checkout@v4
      # - name: Use Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18
      # - name: install packages
      #   run: |
      #     npm i
      # - name: run Lighthouse CI
      #   run: |
      #     npm install
      #     npm install -g @lhci/cli@0.14.0
      #     lhci autorun --collect.staticDistDir="./src" --collect.settings.chromeFlags="--no-sandbox" --upload.target=temporary-public-storage --assert.preset="lighthouse:recommended" || echo "LHCI failed!"
      