name: Lighthouse check
on:
  # workflow_run:
  #   workflows:
  #     - 'Deploy to github page'
  #   types:
  #     - completed
  # workflow_dispatch:
  push:
    branches:
      - master

jobs:
  check-performance:
    runs-on: ubuntu-latest
    steps:
      # lighthouse要跑瀏覽器，會失敗
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      # - run: |
      #     npm i -g lighthouse
      #   shell: bash
      # - name: run lighthouse
      #   run: |
      #     lighthouse https://try-github-actions-git-master-tempura327s-projects.vercel.app/

      # lighthouse-ci
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      # 如果是SSG，就不需要build，所以要把這個step移除
      - name: install packages
        run: |
          npm i
      - name: run Lighthouse CI
        run: |
          npm install
          npm install -g @lhci/cli@0.14.0
          lhci autorun --collect.staticDistDir="./src" --collect.settings.chromeFlags="--no-sandbox" --upload.target=temporary-public-storage --assert.preset="lighthouse:recommended" || echo "LHCI failed!"
        