name: Release Jira release note
on:
  workflow_run:
    workflows:
      - 'Deploy to github page'
    types:
      - completed

jobs:
  update-jira-release-note:
    runs-on: ubuntu-latest
    steps:
      - name: get id of release version
        # uses: tempura327/try-github-actions/.github/workflows/actions/get-jira-project-version@master
        uses: ../actions/get-jira-project-version
        with:
          jiraDomain: ${{secrets.JIRA_DOMAIN}}
          jiraToken: ${{secrets.JIRA_TOKEN}}
          projectKey: TGA
          versionName: ${{github.ref_name}}

      - name: print version
        run: |
          echo $versionName
          echo $versionId

      - name: update jira release note
        uses: ../actions/update-release-note
        with:
          jiraDomain: ${{secrets.JIRA_DOMAIN}}
          jiraToken: ${{secrets.JIRA_TOKEN}}
          versionId: ${{steps.get-id-of-release-version.outputs.versionId}}
          projectId: 10001
