name: Release Jira release note
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  # workflow_run:
  #   workflows:
  #     - 'Deploy to github page'
  #   types:
  #     - completed

  # push:
  #   branches:
  #     - master

jobs:
  update-jira-release-note:
    runs-on: ubuntu-latest
    # if: ${{startsWith(github.ref_name, 'trial@')}}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          npm install
          npm list
        shell: bash

      - name: download version artifact and get saved version
        uses: actions/download-artifact@v4
        with:
          name: github-pages
      
      - name: read versionData file
        run: |
          ls
          # cat ./src/version.txt
          # echo "versionName=$(cat ./src/version.txt)" >> $GITHUB_ENV
          echo ${{inputs.version}}

      - name: get id of release version
        id: get_version
        # uses: tempura327/try-github-actions/.github/actions/get-jira-project-version@master
        # 不會被當作path
        # uses: ../actions/get-jira-project-version
        # 這樣會跑到/home/runner/work/try-github-actions/try-github-actions/.github/actions/get-jira-project-version
        # uses: ./.github/actions/get-jira-project-version
        # 路徑錯誤
        # uses: ./../.github/actions/get-jira-project-version
        uses: ./.github/actions/get-jira-project-version
        with:
          jiraDomain: ${{secrets.JIRA_DOMAIN}}
          jiraToken: ${{secrets.JIRA_TOKEN}}
          projectKey: TGA
          versionName: ${{inputs.version}}

      - name: print version
        run: |
          echo ${{steps.get_version.outputs.versionId}}
          # 不論觸發時機，一直得到master
          echo ${{github.ref_name}}

      - name: update jira release note
        uses: ./.github/actions/update-release-note
        with:
          jiraDomain: ${{secrets.JIRA_DOMAIN}}
          jiraToken: ${{secrets.JIRA_TOKEN}}
          versionId:  ${{steps.get_version.outputs.versionId}}
          projectId: 10001
# this workflow is replaced by release-jira-release-note/action.yml