name: Try JS action

on:
  push:
    branches:
      - master

jobs:
  call_js_action_1:
    runs-on: ubuntu-latest
    needs: call_reusable_workflow_1
    steps:
      - id: trial
        uses: tempura327/try-github-actions@v1.0.2
        with:
          name: 'Tempura Ninja'
      
      - run: |
          echo How\'s it going with your new workflow?
          echo ${{ steps.trial.outputs.reply }}
        shell: bash
