name: Try JS action

on:
  push:
    branches:
      - master

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
      - id: print-somethig
        run: |
          echo "Good morning."


  call_js_action_1:
    runs-on: ubuntu-latest
    steps:
      - id: trial
        uses: tempura327/try-github-actions@v1.0.4
        with:
          name: 'Tempura Ninja'
      
      - run: |
          echo How\'s it going with your new workflow?
          echo ${{ steps.trial.outputs.reply }}
        shell: bash
