name: Try reusable

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  first_job_of_reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: |
          echo Hello ${{ inputs.name }}