name: Try matrix

on:
  push:
    branches:
      - master

jobs:
  # greet-to-someone:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       greeting: ['Have you ever', 'Will you']
  #       action: ['go to ', 'live in']
  #       country: ['Japan', 'Canada', 'Taiwan']
  #   steps:
  #     - name: Greet
  #       run: echo "${{ matrix.greeting }} ${{ matrix.action }} ${{ matrix.country }}?"    

  # prepare-for-dessert:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       fruit: ['mango', 'strawberry', 'blue berry']
  #       base: ['vanilla cake', 'chocolate fudge cake']
  #       include:
  #         - decoration: edible cake flowers
  #         - fruit: raspberry
  #           sauce: caramel sauce
  #   steps:
  #     - name: Prepare for a fancy cake
  #       run: echo "${{ matrix.fruit }} ${{ matrix.base }} with ${{toJSON(matrix.include)}}"

    # greet-to-someone:
    #   runs-on: ubuntu-latest
    #   strategy:
    #     matrix:
    #       greeting: ['Have you ever', 'Will you']
    #       action: ['go to ', 'live at']
    #       country: ['Japan', 'Canada', 'Taiwan']
    #       include:
    #         - country: UK
    #         - time: when the flowers blossom
    #   steps:
    #     - name: Greet
    #       run: echo "${{ matrix.greeting }} ${{ matrix.action }} ${{ matrix.country }}?"

  prepare-dessert:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [mango, strawberry]
        dessert: ['ice cream', cake]
        include:
          - size: small
          - size: large
            dessert: 'ice cream'
          - fruit: mango
            decoration: chocolate
          - fruit: raspberry
          - fruit: raspberry
            dessert: 'ice cream'
    steps:
      - name: ready
        run: echo "${{ matrix.fruit }} ${{ matrix.dessert }} ${{ matrix.decoration }} ${{ matrix.size }}"