name: Try JS action

on:
  push:
    branches:
      - master

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
      # clone repo才讀得到package.json
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          npm install
          npm list


  call_js_action_1:
    runs-on: ubuntu-latest
    steps:
      - id: trial
        # uses: tempura327/try-github-actions@master
        # with:
        #   name: 'Tempura Ninja'
        run: |
          cd ../
          ls
          node .github/actions/js-actions/index.js
      
      - run: |
          echo How\'s it going with your new workflow?
          echo ${{ steps.trial.outputs.reply }}
        shell: bash
