name: Try caller

on:
  push:
    branches:
      - master

jobs:
  call_reusable_workflow_1:
    uses: tempura327/try-github-actions/.github/workflows/try-reusable-1.yml@master
    with:
      name: Tempura327

  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: |
          echo How\'s it going with your new workflow?
          echo ${{ needs.call_reusable_workflow_1.outputs.ANSWER }}
