name: Try1

on:
  push:
    branches: 
      - main

env:
  str: "{\"name\":\"Tempura\"}"

defaults:
  run:
    working-directory: compiler

jobs:
  playground:
    name: Test job1
    runs-on: ubuntu-latest
    steps:
      - name: first
        run: |
          echo ${{toJSON(str)}}
          echo ${{fromJSON({\"name\": \"Tempura\"})}}
     