name: Try

on:
  push:
    branches:
      - master
  
env:
  str1: "{\"name\":\"Tempura\", \"jobs\":{\"fullTime\":\"frontend developer\", \"partTime\":\"no\"}, \"favorites\":[\"tempura ninja\"]}"
  str2: '[{"name":"Tempura"}, {"name":"Ninja"}]'
  str3: "{\"name\":\"Tempura\"}"

jobs:
  discover_yarn_workspaces:
    name: Discover yarn workspaces
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: s1
        run: | 
          echo ${{fromJSON(env.str1)}}
          echo ${{fromJSON(env.str2)}}
          echo ${{fromJSON(env.str3)}}

      # - name: s2
        # run: | 
          # toJSON處理物件、陣列會報錯 "line 2: name:: command not found"
          # echo ${{toJSON(fromJSON(env.str3))}}
          # echo ${{toJSON(fromJSON(env.str2))}}

      - name: s3
        run: | 
          echo ${{fromJSON(env.str1).name}}
          echo ${{fromJSON(env.str1).jobs}}
          echo ${{fromJSON(env.str1).favorites}}
          echo ${{fromJSON(env.str2).*.name}}
          echo ${{fromJSON(env.str2)[0]}}
          echo ${{fromJSON(env.str2)[0].name}}

      - name: try to access undefined property
        run: |  
          # 以下屬性一定不存在
          # 得到undefined
          echo ${{fromJSON(env.str1).xxx}}
          echo ${{fromJSON(env.str1).xxx == null}}
          # 得到陣列
          echo ${{fromJSON(env.str2).*.xxx}}
          echo "----------"
          echo ${{fromJSON(env.str2).*.xxx[0]}}
          echo ${{fromJSON(env.str2).*.xxx[0][0][0][0][0][0][0][0][0][0][0][0]}}
          # 確認是不是null
          echo ${{fromJSON(env.str2).*.xxx[0] == null}}
          echo "----------"
          echo ${{fromJSON(env.str2).*.xxx == '[]'}}
          echo ${{fromJSON(env.str2).*.xxx != '[]'}}
          echo ${{fromJSON(env.str2).*.xxx == '[undefined, undefined]'}}

      - name: try to find out length
        run: |
        # https://github.com/orgs/community/discussions/27125
        # https://stackoverflow.com/questions/68032967/check-for-element-in-an-array-in-github-action-script